### ISSUE TITLE
Use postcss-load-config instead of .babelrc

### ISSUE THREAD

**Issue by DenisIzmaylov** [lttb/babel-plugin-prejss#2]
Dear,
Thank you very much for great plugin! 

It would be great to use https://github.com/michael-ciniawsky/postcss-load-config instead of `.babelrc`

In this case we could use the shared config with https://github.com/axept/jss-from-postcss

Also it will help to keep consistent behaviour of the both plugins in tandem.

**Comment by lttb** [comment]
Thank you! Done!

And I also decided not to use fallback config for PostCSS in this plugin, so you **must** to set PostCSS config somehow according to [postcss-load-config](https://github.com/michael-ciniawsky/postcss-load-config).

**Comment by DenisIzmaylov** [comment]
Perfectly great! Thanks for fast reaction.
