### ISSUE TITLE
Support TaggedTemplateExpression with configurable 

### ISSUE THREAD

**Issue by DenisIzmaylov** [lttb/babel-plugin-prejss#3]
Dear,
Thanks again for your plugin!

It would be great to support `TaggedTemplateExpression` with configurable function names.

Like that:

+ https://github.com/threepointone/glamor/blob/master/src/css/babel.js#L153

It helps to use this plugin together with https://github.com/axept/jss-from-postcss#adapters

**Comment by lttb** [comment]
Thanks! Yep, it would be useful I think.

I'll try to implement it soon

**Comment by lttb** [comment]
Done!

Please check an [example](https://github.com/lttb/babel-plugin-prejss/blob/d17a5ff74edd56246234704250ff2467f2f5d24f/examples/counter/src/client/components/Counter/index.jsx#L29)
